- hosts: ["localhost"]
  # become: true
  tasks:
    - include: ./tasks/general.yml
      tags:
      - general
      - all
    - include: ./tasks/extras.yml
      tags:
      - extras
      - all
    - include: ./tasks/javascript.yml
      tags:
      - javascript
      - all
    - include: ./tasks/java.yml
      tags:
      - java
      - all
