- name: Install FZF
  community.general.homebrew:
    name: fzf
    state: present
  tags:
  - never
- name: Install HTOP
  community.general.homebrew:
    name: htop
    state: present
  tags:
  - never
- name: Install Terminal TLDR
  community.general.homebrew:
    name: tldr
    state: present
  tags:
  - never