- name: Check Oh My Zsh Installation
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: omz_path
  tags:
  - omz
  - terminal
  - general
- name: Install Oh My Zsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
  - omz
  - terminal
  - general
  when: not omz_path.stat.exists
- name: Install Slack
  community.general.homebrew_cask:
    name: slack
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install ITerm2
  community.general.homebrew_cask:
    name: iterm2
    state: present
    accept_external_apps: true
  tags:
  - general
  - terminal
- name: Install Docker
  community.general.homebrew_cask:
    name: docker
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install Postman
  community.general.homebrew_cask:
    name: postman
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install Chrome
  community.general.homebrew_cask:
    name: google-chrome
    state: present
    accept_external_apps: true
  tags:
    - general
    - core
- name: Install Zoom
  community.general.homebrew_cask:
    name: zoom
    state: present
    accept_external_apps: true
  tags:
    - general