- name: Install Oh My Zsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - zsh
    - general
- name: Install HomeBrew
  shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh
  tags:
    - brew
    - general
- name: Update HomeBrew
  community.general.homebrew:
    update_homebrew: yes
  tags:
    - brew
    - general
