- name: Install Oh My Zsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - terminal
    - general
- name: Install Slack
  community.general.homebrew_cask:
    name: slack
    state: present
  tags:
    - general
    - core
- name: Install ITerm2
  community.general.homebrew_cask:
    name: iterm2
    state: present
  tags:
    - general
    - terminal
- name: Install Docker
  community.general.homebrew_cask:
    name: docker
    state: present
  tags:
    - general
    - core
- name: Install Postman
  community.general.homebrew_cask:
    name: postman
    state: present
  tags:
    - general
    - core
