- name: Check Oh My Zsh Installation
  shell: >
    [ ! $(command -v omz) ] | echo
  register: omz_install
  tags:
  - omz
  - terminal
  - general
- name: Install Oh My Zsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  when: omz_install|bool
  tags:
  - omz
  - terminal
  - general
- name: Install Slack
  community.general.homebrew_cask:
    name: slack
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install ITerm2
  community.general.homebrew_cask:
    name: iterm2
    state: present
    accept_external_apps: true
  tags:
  - general
  - terminal
- name: Install Docker
  community.general.homebrew_cask:
    name: docker
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install Postman
  community.general.homebrew_cask:
    name: postman
    state: present
    accept_external_apps: true
  tags:
  - general
  - core
- name: Install Chrome
  community.general.homebrew_cask:
    name: google-chrome
    state: present
    accept_external_apps: true
  tags:
    - general
    - core
- name: Install Zoom
  community.general.homebrew_cask:
    name: zoom
    state: present
    accept_external_apps: true
  tags:
    - general