- name: Download VSCode
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
    accept_external_apps: true
  tags:
  - frontend
  - vscode
- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
  - frontend
  - node
  - nvm
- name: Set default global packages
  shell: echo "typescript\nyarn\n" > "{{ ansible_env.HOME }}/.nvm/default-packages"
  args:
    creates: "{{ansible_env.HOME}}/.nvm/default-packages"
  tags:
  - frontend
  - node
  - nvm
- name: Install Node
  # need to update the PATH with NVM before installing node
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 14
  args:
    creates: "{{ansible_env.HOME}}/.nvm/alias"
  tags:
  - frontend
  - node
  - nvm
