- name: Tap AdoptOpenJdk
  community.general.homebrew_tap:
    name: adoptopenjdk/openjdk
    state: present
  tags:
  - backend
  - java_language
- name: Install Java
  community.general.homebrew_cask:
    name: adoptopenjdk11
    state: present
    accept_external_apps: true
  tags:
  - backend
  - java_language
- name: Install IntelliJ Idea
  community.general.homebrew_cask:
    name: intellij-idea
    state: present
    accept_external_apps: true
  tags:
  - backend
  - intellij